services:
  guitarapp-nginx:
    container_name: "guitarapp-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - guitarapp-app
    ports:
      - 80:80
    volumes:
      - ./:/src
    tty: true

  guitarapp-app:
    container_name: "guitarapp-app"
    build:
      context: ./docker/php
    depends_on:
      - guitarapp-mysql
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  guitarapp-mysql:
    image: mysql:8.0.37
    command: --max_allowed_packet=32505856
    container_name: "guitarapp-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=l11dev
    ports:
      - 3306:3306

  guitarapp-redis:
    image: redis:alpine
    container_name: "guitarapp-redis"
    ports:
      - 16379:6379
